export const mockDb = {
  users: [
    { email: 'admin', role: 'admin', name: 'Admin User', cover_image: 'https://via.placeholder.com/150' },
    { email: 'user', role: 'user', name: 'Standard User', cover_image: 'https://via.placeholder.com/150' },
    { email: 'doctor', role: 'doctor', name: 'Dr. Hasan Mahmud', cover_image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=300' },
  ],
  specialties: [
    'Cardiology',
    'Ophthalmology',
    'Pediatrics',
    'Dentistry',
    'Neurology',
    'Orthopedics',
    'General Medicine'
  ],
  doctors: [
    {
      _id: 'doc_1',
      name: 'Dr. Hasan Mahmud',
      email: 'doctor',
      specialty: 'Ophthalmology',
      roomNo: 'Room 102',
      isAvailable: true,
      maxTokensPerDay: 40,
      avgConsultTimeMinutes: 12,
      imageUrl: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&q=80&w=300',
      phone: '+880 1711-223344',
      bio: 'Senior Ophthalmologist with over 12 years of experience in corneal and vision care.',
      unavailableTimings: []
    },
    {
      _id: 'doc_2',
      name: 'Dr. Rina Akter',
      email: 'rina@medicamp.org',
      specialty: 'Dentistry',
      roomNo: 'Room 205',
      isAvailable: true,
      maxTokensPerDay: 35,
      avgConsultTimeMinutes: 15,
      imageUrl: 'https://images.unsplash.com/photo-1594824813566-88855ce78961?auto=format&fit=crop&q=80&w=300',
      phone: '+880 1812-345678',
      bio: 'Expert Dental Surgeon specializing in restorative dentistry and cosmetic smiles.',
      unavailableTimings: []
    },
    {
      _id: 'doc_3',
      name: 'Dr. A.K. Azad',
      email: 'azad@medicamp.org',
      specialty: 'Cardiology',
      roomNo: 'Room 301',
      isAvailable: true,
      maxTokensPerDay: 30,
      avgConsultTimeMinutes: 20,
      imageUrl: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&q=80&w=300',
      phone: '+880 1913-987654',
      bio: 'Consultant Cardiologist specializing in interventional cardiology and preventive heart care.',
      unavailableTimings: []
    },
    {
      _id: 'doc_4',
      name: 'Dr. Shireen Begum',
      email: 'shireen@medicamp.org',
      specialty: 'Pediatrics',
      roomNo: 'Room 108',
      isAvailable: false,
      maxTokensPerDay: 45,
      avgConsultTimeMinutes: 10,
      imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=300',
      phone: '+880 1614-112233',
      bio: 'Lead Pediatric Specialist focusing on child developmental care and preventive medicine.',
      unavailableTimings: ['13:00 - 14:00 (Lunch Break)']
    }
  ],
  queueTokens: [
    {
      _id: 'tok_101',
      tokenNumber: 'OPH-001',
      doctorId: 'doc_1',
      doctorName: 'Dr. Hasan Mahmud',
      specialty: 'Ophthalmology',
      roomNo: 'Room 102',
      patientName: 'Karem Hossain',
      patientPhone: '+8801700112233',
      patientEmail: 'user',
      age: 42,
      gender: 'Male',
      medicalNotes: 'Blurred vision in left eye for 3 days',
      status: 'In Consultation', // Waiting, Calling, In Consultation, Completed, Skipped, Cancelled
      isEmergency: false,
      createdAt: new Date(Date.now() - 35 * 60000).toISOString(),
      servingTime: new Date(Date.now() - 5 * 60000).toISOString()
    },
    {
      _id: 'tok_102',
      tokenNumber: 'OPH-002',
      doctorId: 'doc_1',
      doctorName: 'Dr. Hasan Mahmud',
      specialty: 'Ophthalmology',
      roomNo: 'Room 102',
      patientName: 'Standard User',
      patientPhone: '+8801899887766',
      patientEmail: 'user',
      age: 28,
      gender: 'Female',
      medicalNotes: 'Routine eye test & prescription check',
      status: 'Calling',
      isEmergency: false,
      createdAt: new Date(Date.now() - 25 * 60000).toISOString()
    },
    {
      _id: 'tok_103',
      tokenNumber: 'OPH-003',
      doctorId: 'doc_1',
      doctorName: 'Dr. Hasan Mahmud',
      specialty: 'Ophthalmology',
      roomNo: 'Room 102',
      patientName: 'Emergency Patient - Anis',
      patientPhone: '+8801555443322',
      patientEmail: 'anis@example.com',
      age: 55,
      gender: 'Male',
      medicalNotes: 'Acute chemical splash in eye - URGENT',
      status: 'Waiting',
      isEmergency: true,
      createdAt: new Date(Date.now() - 10 * 60000).toISOString()
    },
    {
      _id: 'tok_104',
      tokenNumber: 'OPH-004',
      doctorId: 'doc_1',
      doctorName: 'Dr. Hasan Mahmud',
      specialty: 'Ophthalmology',
      roomNo: 'Room 102',
      patientName: 'Nusrat Jahan',
      patientPhone: '+8801677889900',
      patientEmail: 'nusrat@example.com',
      age: 31,
      gender: 'Female',
      medicalNotes: 'Dry eye consultation',
      status: 'Waiting',
      isEmergency: false,
      createdAt: new Date(Date.now() - 5 * 60000).toISOString()
    },
    {
      _id: 'tok_201',
      tokenNumber: 'DEN-001',
      doctorId: 'doc_2',
      doctorName: 'Dr. Rina Akter',
      specialty: 'Dentistry',
      roomNo: 'Room 205',
      patientName: 'Tanvir Rahman',
      patientPhone: '+8801911223344',
      patientEmail: 'tanvir@example.com',
      age: 35,
      gender: 'Male',
      medicalNotes: 'Tooth cavity pain',
      status: 'In Consultation',
      isEmergency: false,
      createdAt: new Date(Date.now() - 40 * 60000).toISOString()
    },
    {
      _id: 'tok_301',
      tokenNumber: 'CAR-001',
      doctorId: 'doc_3',
      doctorName: 'Dr. A.K. Azad',
      specialty: 'Cardiology',
      roomNo: 'Room 301',
      patientName: 'Mahbub Alam',
      patientPhone: '+8801733445566',
      patientEmail: 'mahbub@example.com',
      age: 62,
      gender: 'Male',
      medicalNotes: 'Chest discomfort & blood pressure review',
      status: 'Waiting',
      isEmergency: false,
      createdAt: new Date(Date.now() - 15 * 60000).toISOString()
    }
  ],
  queueSettings: {
    maxTokensPerDoctor: 40,
    avgConsultationTimeMinutes: 15,
    autoCancelInactiveMinutes: 30,
    enableEmergencyPriority: true,
    hospitalName: 'MediCamp Central Hospital',
    operatingHours: '08:00 AM - 08:00 PM'
  },
  camps: [
    {
      _id: 'camp_1',
      name: 'Free Eye Camp',
      imageUrl: 'https://res.cloudinary.com/dv6p7mprd/image/upload/v1752088744/close-up-health-worker_gt09sx.jpg',
      fees: 0,
      date: '2026-08-15',
      time: '10:00 AM',
      location: 'Dhaka Medical College',
      healthcareProfessionalName: 'Dr. Hasan Mahmud',
      participantCount: 120,
      description: 'A comprehensive free eye checkup camp for all ages. We provide free basic medication and glasses to those in need.',
      searchKeyWords: 'free eye camp dhaka medical college ophthalmology vision'
    },
    {
      _id: 'camp_2',
      name: 'Dental Care Camp',
      imageUrl: 'https://images.unsplash.com/photo-1606811841689-23dfddce3e95?auto=format&fit=crop&q=80&w=600',
      fees: 50,
      date: '2026-08-20',
      time: '09:00 AM',
      location: 'Banani Clinic',
      healthcareProfessionalName: 'Dr. Rina Akter',
      participantCount: 85,
      description: 'Comprehensive dental checkup, cleaning, and consultation for better oral hygiene.',
      searchKeyWords: 'dental care camp banani clinic teeth dentistry'
    },
    {
      _id: 'camp_3',
      name: 'Cardiac Awareness Camp',
      imageUrl: 'https://images.unsplash.com/photo-1527613426441-4da17471b66d?auto=format&fit=crop&q=80&w=600',
      fees: 100,
      date: '2026-09-05',
      time: '08:30 AM',
      location: 'National Heart Foundation',
      healthcareProfessionalName: 'Dr. A.K. Azad',
      participantCount: 150,
      description: 'Heart health screening, ECG, and consultation with top cardiologists to raise awareness about cardiovascular diseases.',
      searchKeyWords: 'cardiac awareness camp national heart foundation cardiology ecg'
    },
    {
      _id: 'camp_4',
      name: 'Pediatric Health Checkup',
      imageUrl: 'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&q=80&w=600',
      fees: 20,
      date: '2026-09-12',
      time: '11:00 AM',
      location: 'Shishu Hospital',
      healthcareProfessionalName: 'Dr. Shireen Begum',
      participantCount: 200,
      description: 'Specialized health camp focusing on child nutrition, vaccination, and overall pediatric well-being.',
      searchKeyWords: 'pediatric health checkup shishu hospital child baby kids'
    },
    {
      _id: 'camp_5',
      name: 'Diabetes Screening & Management',
      imageUrl: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=600',
      fees: 30,
      date: '2026-09-25',
      time: '07:30 AM',
      location: 'BIRDEM General Hospital',
      healthcareProfessionalName: 'Dr. Tariqul Islam',
      participantCount: 310,
      description: 'Fasting blood sugar tests, HbA1c screening, and dietary advice for diabetic patients.',
      searchKeyWords: 'diabetes screening management birdem general hospital blood sugar'
    },
    {
      _id: 'camp_6',
      name: 'Women\'s Wellness & Gynecology',
      imageUrl: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&q=80&w=600',
      fees: 0,
      date: '2026-10-10',
      time: '10:00 AM',
      location: 'Square Hospital',
      healthcareProfessionalName: 'Dr. Farhana Ahmed',
      participantCount: 250,
      description: 'Free checkups for women including breast cancer screening, prenatal advice, and general gynecology.',
      searchKeyWords: 'womens wellness gynecology square hospital free screening'
    },
    {
      _id: 'camp_7',
      name: 'Mental Health Support Group',
      imageUrl: 'https://images.unsplash.com/photo-1573497620053-ea5300f94f21?auto=format&fit=crop&q=80&w=600',
      fees: 0,
      date: '2026-10-15',
      time: '04:00 PM',
      location: 'Community Center, Dhanmondi',
      healthcareProfessionalName: 'Dr. Kamal Uddin',
      participantCount: 45,
      description: 'A safe space to discuss mental health, anxiety, and depression with professional psychologists.',
      searchKeyWords: 'mental health support group community center dhanmondi psychology therapy'
    },
    {
      _id: 'camp_8',
      name: 'Orthopedic & Joint Pain Clinic',
      imageUrl: 'https://images.unsplash.com/photo-1581594693702-fbdc51b2763b?auto=format&fit=crop&q=80&w=600',
      fees: 150,
      date: '2026-11-02',
      time: '09:30 AM',
      location: 'Apollo Hospitals',
      healthcareProfessionalName: 'Dr. Mostafa Zaman',
      participantCount: 180,
      description: 'Consultation for arthritis, joint pains, and posture correction with free basic physiotherapy sessions.',
      searchKeyWords: 'orthopedic joint pain clinic apollo hospitals bones physiotherapy'
    }
  ],
  registeredCamps: [
    {
      _id: 'reg_1',
      participant_name: 'Standard User',
      participant_email: 'user',
      camp_name: 'Free Eye Camp',
      camp_fee: 0,
      isPayment_confirmed: true,
      isAdmin_approved: true,
      isAdmin_cancel: false
    },
    {
      _id: 'reg_2',
      participant_name: 'Standard User',
      participant_email: 'user',
      camp_name: 'Dental Care Camp',
      camp_fee: 50,
      isPayment_confirmed: true,
      isAdmin_approved: false,
      isAdmin_cancel: false
    },
    {
      _id: 'reg_3',
      participant_name: 'Rahim Sheikh',
      participant_email: 'rahim@example.com',
      camp_name: 'Diabetes Screening & Management',
      camp_fee: 30,
      isPayment_confirmed: true,
      isAdmin_approved: true,
      isAdmin_cancel: false
    },
    {
      _id: 'reg_4',
      participant_name: 'Fatima Akter',
      participant_email: 'fatima@example.com',
      camp_name: 'Women\'s Wellness & Gynecology',
      camp_fee: 0,
      isPayment_confirmed: false,
      isAdmin_approved: false,
      isAdmin_cancel: false
    },
    {
      _id: 'reg_5',
      participant_name: 'Kamal Hossain',
      participant_email: 'kamal@gmail.com',
      camp_name: 'Cardiac Awareness Camp',
      camp_fee: 100,
      isPayment_confirmed: true,
      isAdmin_approved: true,
      isAdmin_cancel: false
    },
    {
      _id: 'reg_6',
      participant_name: 'Nusrat Jahan',
      participant_email: 'nusrat@yahoo.com',
      camp_name: 'Pediatric Health Checkup',
      camp_fee: 20,
      isPayment_confirmed: true,
      isAdmin_approved: false,
      isAdmin_cancel: false
    },
    {
      _id: 'reg_7',
      participant_name: 'Tariqul Islam',
      participant_email: 'tariq@outlook.com',
      camp_name: 'Orthopedic & Joint Pain Clinic',
      camp_fee: 150,
      isPayment_confirmed: false,
      isAdmin_approved: false,
      isAdmin_cancel: false
    },
    {
      _id: 'reg_8',
      participant_name: 'Sabrina Yeasmin',
      participant_email: 'sabrina@hotmail.com',
      camp_name: 'Mental Health Support Group',
      camp_fee: 0,
      isPayment_confirmed: true,
      isAdmin_approved: true,
      isAdmin_cancel: false
    }
  ],
  payments: [
    {
      _id: 'pay_1',
      transactionId: 'TXN_001',
      email: 'user',
      campName: 'Dental Care Camp',
      campFees: 50,
      date: new Date().toISOString(),
      status: 'success'
    }
  ]
};

